---
variables:
  LATEX_IMAGE: registry.gitlab.com/bindrpg/config:latest

build:
  image: $LATEX_IMAGE
  script:
    - make -j 3 -O all
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_BRANCH == "run"
  artifacts:
    paths:
      - "*.pdf"
