compile_pdf:
  image: aergus/latex
  script:
    - apt-get update -y
    - apt-get install -y inkscape
    - make
    - make resources
    - mv main.pdf bind.pdf
  only:
    - master
    - run
  artifacts:
    paths:
      - bind.pdf
      - resources.pdf
