compile_pdf:
  image: ctornau/latex
  script:
    - apt-get update -y
    - apt-get install -y inkscape make
    - make
    - make resources
    - make ref
    - mv main.pdf bind.pdf
  only:
    - master
    - run
  artifacts:
    paths:
      - bind.pdf
      - resources.pdf
      - bind_ref.pdf
